<?php
/**
 * Class that represents database table '${table_name}'
 * This class is generated by PHPDAO, and will be overwritten.
 *
 * @version 2.7
 * @date ${date}
 *
 * Original author
 * @author http://phpdao.com
 * 
 * Revision 2.7
 * @author Aaron Bean <aaron.bean@beardon.com>
 */
class ${class_name} {
	${variables}		
}