<?php
/**
 * Static class that can execute stored functions and procedures
 * This class is generated by PHPDAO, and will be overwritten.
 *
 * @version 2.7
 * @date ${date}
 *
 * @author Aaron Bean <aaron.bean@beardon.com>
 */
class StoredRoutines {
${functions}		
}